//! SSH connection-protocol message type numbers and small helpers (RFC 4254 §9).

/// `SSH_MSG_GLOBAL_REQUEST` (80).
pub const MSG_GLOBAL_REQUEST: u8 = 80;
/// `SSH_MSG_REQUEST_SUCCESS` (81).
pub const MSG_REQUEST_SUCCESS: u8 = 81;
/// `SSH_MSG_REQUEST_FAILURE` (82).
pub const MSG_REQUEST_FAILURE: u8 = 82;

/// `SSH_MSG_CHANNEL_OPEN` (90).
pub const MSG_CHANNEL_OPEN: u8 = 90;
/// `SSH_MSG_CHANNEL_OPEN_CONFIRMATION` (91).
pub const MSG_CHANNEL_OPEN_CONFIRMATION: u8 = 91;
/// `SSH_MSG_CHANNEL_OPEN_FAILURE` (92).
pub const MSG_CHANNEL_OPEN_FAILURE: u8 = 92;
/// `SSH_MSG_CHANNEL_WINDOW_ADJUST` (93).
pub const MSG_CHANNEL_WINDOW_ADJUST: u8 = 93;
/// `SSH_MSG_CHANNEL_DATA` (94).
pub const MSG_CHANNEL_DATA: u8 = 94;
/// `SSH_MSG_CHANNEL_EXTENDED_DATA` (95).
pub const MSG_CHANNEL_EXTENDED_DATA: u8 = 95;
/// `SSH_MSG_CHANNEL_EOF` (96).
pub const MSG_CHANNEL_EOF: u8 = 96;
/// `SSH_MSG_CHANNEL_CLOSE` (97).
pub const MSG_CHANNEL_CLOSE: u8 = 97;
/// `SSH_MSG_CHANNEL_REQUEST` (98).
pub const MSG_CHANNEL_REQUEST: u8 = 98;
/// `SSH_MSG_CHANNEL_SUCCESS` (99).
pub const MSG_CHANNEL_SUCCESS: u8 = 99;
/// `SSH_MSG_CHANNEL_FAILURE` (100).
pub const MSG_CHANNEL_FAILURE: u8 = 100;

/// `SSH_EXTENDED_DATA_STDERR` (1) — `data_type_code` for `CHANNEL_EXTENDED_DATA`.
pub const SSH_EXTENDED_DATA_STDERR: u32 = 1;

/// `SSH_OPEN_ADMINISTRATIVELY_PROHIBITED` (1).
pub const SSH_OPEN_ADMINISTRATIVELY_PROHIBITED: u32 = 1;
/// `SSH_OPEN_CONNECT_FAILED` (2).
pub const SSH_OPEN_CONNECT_FAILED: u32 = 2;
/// `SSH_OPEN_UNKNOWN_CHANNEL_TYPE` (3).
pub const SSH_OPEN_UNKNOWN_CHANNEL_TYPE: u32 = 3;
/// `SSH_OPEN_RESOURCE_SHORTAGE` (4).
pub const SSH_OPEN_RESOURCE_SHORTAGE: u32 = 4;
